### PR TITLE
fix frontend error handling

### PR DESCRIPTION
**Pull request by yiyinglovecoding**
as title

test excution in https://screenshot.googleplex.com/9hukv5EKMoBw8wK

one more test : https://screenshot.googleplex.com/AKSWnxnEMLpiKQz

### CODE REVIEW

**Review by blackzlq — CHANGES_REQUESTED** [review]
Please build local image and test it.

**Comment by yiyinglovecoding** [comment]
> Please build local image and test it.

add the test screenshot executing the changed line

**Pull request closed without merging**
