### PR TITLE
Update frontend image

### PR DESCRIPTION
**Pull request by blackzlq**
consume the latest change

Tested-by: No test

### CODE REVIEW

**Review by imreddy13 — APPROVED** [review]

**Comment by yiyinglovecoding** [comment]
@imreddy13  do we want to replace the hash with image tag instead?

**Comment by blackzlq** [comment]
> @imreddy13 do we want to replace the hash with image tag instead?

No, we prefer SHA than tag for the jupyter case we can not use SHA.

**Review by imreddy13 — APPROVED** [review]

**Pull request merged**
