### PR TITLE
Add Stable Diffusion XL inference  using MaxDiffusion

### PR DESCRIPTION
**Pull request by rick-c-goog**
Add Stable Diffusion XL inference on GKE and TPU example use MaxDiffusion 

MaxDiffusion source: 
https://github.com/google/MaxDiffusion

### CODE REVIEW

**Review by Bslabe123 — CHANGES_REQUESTED** [review]
Remove the .DS_store files and I'll approve!

**Comment by rick-c-goog** [comment]
.Data_Store removed

**Comment by rick-c-goog** [comment]
> Remove the .DS_store files and I'll approve!



> Remove the .DS_store files and I'll approve!

Completed

**Review by Bslabe123 — APPROVED** [review]

**Pull request merged**
