### PR TITLE
Vuln bug for pip install. Checksum is required when using pip

### PR DESCRIPTION
**Pull request by chiayi**
As part of the vulnerability fix requirement for using pip install so that we can ensure accurate vulnerability scanning. 
Added a requirements.txt with the necessary hashes.

### CODE REVIEW

**Review by alizaidis — APPROVED** [review]
LGTM

**Review by alizaidis — APPROVED** [review]

**Review by alizaidis — APPROVED** [review]
LGTM

**Comment by chiayi** [comment]
@alizaidis Please reapprove since I made a change to the PR.

**Review by alizaidis — APPROVED** [review]
Approved.

**Comment by alizaidis** [comment]
@kenthua Would appreciate a review.

**Review by kenthua — APPROVED** [review]
lgtm

**Pull request merged**
