### PR TITLE
Pin the terraform import paths on the release branch to the v1.1.2 release tag

### PR DESCRIPTION
**Pull request by roberthbailey**

### CODE REVIEW

**Review by imreddy13 — APPROVED** [review]

**Comment by roberthbailey** [comment]
Actually got a more useful error this time:

```
AssertionError: unexpected response url: got http://127.0.0.1:9443/hub/login?_xsrf=MnwxOjB8MTA6MTcxNDYxNjM2MXw1Ol94c3JmfDY4OlRtOXVaVHB3WlZGeE9VSm5TVlJTVm1WQmFVSnZjR2d4VVRWU2FWQmZiWGxJVGw5QmJuVTNja05pUkU4eE1rbFpQUT09fDcwNThmOTM3ZmM0M2JlY2MxMjQzZjQ5MTBhZjk5Mjk0NGYxZWYyNTRlMjY5ODg0MmQ5OTE2MDdjZTI3ZTE0M2M, expected http://127.0.0.1:9443/hub/spawn
```

**Comment by roberthbailey** [comment]
I saw this while I was testing https://github.com/GoogleCloudPlatform/ai-on-gke/pull/643 - it happened when the credentials supplied to the query were incorrect.

**Comment by roberthbailey** [comment]
The failing test reads the username and password from a local file loaded from a relative path (https://github.com/GoogleCloudPlatform/ai-on-gke/blob/main/modules/jupyter/tests/test_hub.py#L7). I'm wondering if something about loading modules remotely from github vs. using modules at relative paths is preventing this file from having the proper credentials set. 

I'm going to abandon this proposed change for now, but wanted to leave some thoughts in case we come back and try to fix this for future releases.

**Pull request closed without merging**
