### PR TITLE
Distributed ML training on GPUs using Indexed Jobs on GKE

### PR DESCRIPTION
**Pull request by danielvegamyhre**
Distributed ML training on GPUs using Indexed Jobs on GKE.

I tested the steps in this guide manually and confirmed they work as expected.

cc @ahg-g

### CODE REVIEW

**Comment by danielvegamyhre** [comment]
cc @richardsliu

**Comment by ahg-g** [comment]
Thanks Daniel, can we squash pls?

**Comment by danielvegamyhre** [comment]
@ahg-g I squashed the commits

**Comment by danielvegamyhre** [comment]
@ahg-g we need someone with approval powers to merge it. @richardsliu can you review/merge this please?

**Pull request merged**
