### PR TITLE
Define ephemeral-storage in ClusterQueue

### PR DESCRIPTION
**Pull request by dsafdsa1**
Support workloads requesting ephemeral-storage, and match the ResourceFlavor in https://cloud.google.com/kubernetes-engine/docs/tutorials/kueue-intro#create_the_resourceflavor

### CODE REVIEW

**Comment by mimowo** [comment]
LGTM
Thanks!

**Comment by dsafdsa1** [comment]
@spencer-p can you lgtm/approve please? @mimowo doesn't have permissions to approve or add lgtm.

**Review by spencer-p — APPROVED** [review]

**Pull request merged**
