### PR TITLE
Add Kueue exemplary setup for reservation and DWS

### PR DESCRIPTION
**Pull request by PBundyra**
Added Kueue exemplary setup which uses reservation nodepool first, and if there is no capacity in reservation, then tries DWS.

### CODE REVIEW

**Review by alculquicondor — COMMENTED** [review]
/lgtm
/approve

**Review by alculquicondor — APPROVED** [review]

**Comment by andrewsykim** [comment]
The cloud build presubmit can be ignored for this PR since we don't test the DWS example there

**Pull request merged**
