### PR TITLE
Set the namespace in the sample configurations for the rag, ray, & jupyter applications to `ai-on-gke`

### PR DESCRIPTION
**Pull request by roberthbailey**

### CODE REVIEW

**Review by andrewsykim — COMMENTED** [review]
Also update https://github.com/GoogleCloudPlatform/ai-on-gke/blob/main/applications/rag/metadata.yaml#L190?

**Comment by roberthbailey** [comment]
Thanks. I've now also included the files in the `applications/rag` directory.

**Review by andrewsykim — APPROVED** [review]

**Pull request merged**
